- name: Create stolon-sentinel user
  user:
      name: "{{ stolon_sentinel_user }}"
      home: "/home/{{ stolon_sentinel_user }}"
      state: present
      group: postgres

- name: Change user dir permissions
  file: 
      path: "/home/{{ stolon_sentinel_user }}"
      state: directory
      mode: 0750
      group: postgres

- name: Create postgres pass file
  become: yes
  become_method: sudo
  template: 
      src: postgres.pf.j2
      dest: "{{ stolon_su_passwordfile }}"
      mode: 0440
      group: postgres

- name: Create replication pass file
  become: yes
  become_method: sudo
  template: 
      src: replication.pf.j2
      dest: "{{ stolon_repl_passwordfile }}"
      mode: 0440
      group: postgres

