
- name: Register the current Stolon version (if any)
  command: /usr/stolon/bin/stolonctl --version
  ignore_errors: yes
  register: stolon_version_check
  changed_when: false
- name: Download stolon
  get_url:
    url: "https://github.com/sorintlab/stolon/releases/download/v{{ stolon_version }}/stolon-v{{ stolon_version }}-linux-amd64.tar.gz"
    dest: "/tmp/stolon.tar.gz"

- name: Remove old installation of Stolon
  become: yes
  become_method: sudo
  file:
    path: "{{ stolon_unarchive_prefix }}"
    state: absent

- name: Check work dir | {{ stolon_unarchive_prefix }}
  become: yes
  become_method: sudo
  file:
    path: "{{ stolon_unarchive_prefix }}"
    state: directory
    mode: 755

- name: Extract stolon
  become: yes
  become_method: sudo
  ansible.builtin.unarchive:
    src: "/tmp/stolon.tar.gz"
    dest: /tmp/
    remote_src: yes
    extra_opts: --no-same-owner
  
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: "/tmp/stolon-v{{ stolon_version }}-linux-amd64/bin/"
    dest: "{{ stolon_unarchive_prefix }}"
    mode: '0644'

- name: Remove archive
  file:
    path: "/tmp/stolon-v{{ stolon_version }}-linux-amd64.tar.gz"
    state: absent

  when: stolon_version_check is failed or stolon_version_check.stdout != stolonctl_version_target


