- name: Install PostgreSQL and contrib packages
  become: yes
  become_method: sudo
  apt:
    name:
      - "postgresql-{{ postgresql_version }}"
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    state: present
    update_cache: yes


- name: Check if PostgreSQL is initialized
  become: yes
  become_method: sudo
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/pg_hba.conf"
  register: postgres_data


- name: Empty data dir
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    state: absent
  when: not postgres_data.stat.exists

- name: Initialize PostgreSQL
  become: yes
  become_method: sudo
  ansible.builtin.shell: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
  become: true
  become_user: postgres
  when: not postgres_data.stat.exists

- name: Start and enable service
  become: yes
  become_method: sudo
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true