# postgres variables
postgresql_version: 14
postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"

# etcd variables
etcd_listen_address: 127.0.0.1
etcd_listen_port: 2379

# stolon variables
stolon_version: 0.17.0
stolon_cluster_name: test
stolon_store_backend: etcdv3
stolon_store_endpoints: "{{ etcd_listen_address }}:{{ etcd_listen_port }}"
stolon_keeper_name: "{{ ansible_hostname }}"
stolon_sentinel_user: stolon-user
stolon_postgres_listen: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
stolon_postgres_port: 5432
stolon_unarchive_prefix: "/usr/stolon"

# stolon user
stolon_sentinel_user: stolon
stolon_postgres_password: Kuux5cuo
stolon_su_passwordfile: "/home/{{ stolon_sentinel_user }}/stolon_postgres.pf"

# stolon replication
stolon_replication_user: replication
stolon_repl_passwordfile: "/home/{{ stolon_sentinel_user }}/stolon_replication.pf"
stolon_replication_password: Aexaix1E