---
- name: "Install etcd"
  become: yes
  apt:
    name: etcd
    update_cache: yes
    state: present
  tags: packages 

- name: Start and enable etcd service
  become: yes
  ansible.builtin.service:
    name: etcd
    state: started
    enabled: true
