---

  - name: Update APT package index
    become: yes
    become_method: sudo
    apt:
        update_cache: yes

  - name: Install required dependencies
    become: yes
    become_method: sudo
    apt:
     name: ['wget', 'tar']
     state: present

  - name: Download etcd
    get_url:
     url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
     dest: "/tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"

  - name: Extract etcd
    become: yes
    become_method: sudo
    unarchive:
      src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
      dest: "/usr/local/bin/"
      remote_src: yes

  - name: Move etcd and etcdctl to /usr/local/bin
    become: yes
    become_method: sudo
    ansible.builtin.shell: mv /usr/local/bin/etcd-v{{ etcd_version }}-linux-amd64/{etcd,etcdctl}  /usr/local/bin/

    args:
       executable: /bin/bash

   
   

  - name: Create etcd user
    become: yes
    become_method: sudo
    user:
     name: etcd
     system: yes
     shell: /sbin/nologin

  - name: Create etcd data directory
    become: yes
    become_method: sudo
    file:
     path: "{{ item }}"
     state: directory
     owner: etcd
     group: etcd
     mode: '0755'
    loop:
      - /etc/etcd
      - /var/lib/etcd
    tags: create_dir

  - name: Create etcd systemd service file
    become: yes
    become_method: sudo
    template:
      src: etcd-service.j2
      dest: /etc/systemd/system/etcd.service
      owner: etcd
      group: etcd
    


  - name: Reload systemd
    become: yes
    become_method: sudo
    systemd:
      daemon_reload: yes

  - name: Enable and start etcd service
    become: yes
    become_method: sudo
    systemd:
      name: etcd
      enabled: yes
      state: started
    tags: start_etcd


  - name: copy etcd file into /etc/default
    become: yes
    become_method: sudo
    template:
      src: etcd.j2
      dest: /etc/default/etcd
      owner: etcd
      group: etcd
    tags: copy_etcd 




  - name: copy etcd-compact.sh file into /opt
    become: yes
    become_method: sudo
    template:
      src: etcd-compact.j2
      dest: /opt/etcd-compact.sh
      owner: root
      group: root
      mode: a+x
    tags: copy_etcd_compact

  - name: etcd-compact cronjob
    become: yes
    become_method: sudo
    cron:
      name: "run etcd-compact.sh"
      user: "root"
      minute: "0"
      hour: "0"
      day: "*"
      month: "*"
      weekday: "*"
      job: "/bin/bash  /opt/etcd-compact.sh"
    tags: cron